# Generated by Django 4.2.23 on 2025-08-25 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_like_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='myapp.article'),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('article', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('article', 'user')},
        ),
    ]
